name: CI to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AMD64
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tesmart-homekit:latest-amd64
          no-cache: true

      - name: Create manifest
        run: docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/tesmart-homekit:latest ${{ secrets.DOCKER_HUB_USERNAME }}/rack-controller:latest-amd64

      - name: Push manifest
        run: docker manifest push --purge ${{ secrets.DOCKER_HUB_USERNAME }}/tesmart-homekit:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}